"""add listing_id to notifications

Revision ID: 143fc26e2603
Revises: 79c1aa17109f
Create Date: 2026-09-14 08:15:13.594286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '143fc26e2603'
down_revision: Union[str, Sequence[str], None] = '79c1aa17109f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('listing_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'listings', ['listing_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'listing_id')
    # ### end Alembic commands ###
